development:
  adapter: mysql2
  encoding: utf8
  database: higgins_development
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: higgins_test
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: higgins_production
  username: root
  password:
